### PR TITLE
Added Alerts

### PR DESCRIPTION
**Pull request by SukanyaSen530**
Added 4 variants of alerts. 
   a. Warning
   b. Success 
   c. Error
   d. Info

4 Types ->
   a.  Basic Alerts
   b. Outline alerts
   c. Filled Alerts
   d. Action Alerts with cancel button

Alerts

### CODE REVIEW

**Review by ishapatell1 — APPROVED** [review]
Looks good sukanya. Ready to merge with the development branch.

**Comment by cjinc121** [comment]
looks good

**Review by cjinc121 — APPROVED** [review]
looks good

**Review by biswanath-tewari — APPROVED** [review]
looks all good.

**Pull request merged**
