### PR TITLE
Added Cards, Rating and Text Badge

### PR DESCRIPTION
**Pull request by SukanyaSen530**
Added Cards -
  a. Text Only Card
  b. Media Card (Vertical)
  c. Media Card (Horizontal)
  d. Card with Shadow
  e. Card with Dismiss Button
  f. Card with Text Overlay
  g. Card with Badge 
  
Added Rating - 
  a. Normal Rating
  b. Average Rating

Badge -
  a. Text Badge (For Card with badge)

Button -
 Made some small changes in padding to use it in card.

Untitled

### CODE REVIEW

**Review by VLeads — APPROVED** [review]
Code looks good.

**Review by cjinc121 — APPROVED** [review]
you can go ahead with merging

**Review by VLeads — APPROVED** [review]

**Review by VLeads — APPROVED** [review]
Looking clean

**Review by VLeads — APPROVED** [review]

**Review by nerdyspook — APPROVED** [review]
The code looks good, you can merge

**Review by SanjayJatti — APPROVED** [review]
Code is clean and all looking fine.

**Pull request merged**
